** Tasks
*** Dotfiles
***** TODO replace simple git repos with submodules -> only done for non-offensive git repos
***** TODO work on git init script which initializes all submodules where necessary before stowing

***** fine-tune the leftover files by improving code quality
***** zsh/bash/tmux improved configurations with display of virtual environment
***** check for ranger and neomutt and other commands before setting up code/functions in shellrc's 
***** change background name to simpler one and synchronize throughout all references

*** System reproducibility
***** TODO extract all steps list in i3 config file for reproducibility
***** work on install script which setps up all the necessary git repos for dotfiles that cannot be managed with submodules -> eg. vim, spacemacs etc.
***** work on update script which updates all submodules to latest commits, and also updates misc. code bases such as melpa, vim, etc.
***** keep gnupg, ssh, neomutt and other directories in a private stow repo

** Completed
*** DONE Design non-offending stow command for all -> put this in readme
    CLOSED: [2020-11-04 Wed 16:14]
*** DONE Dotfile initiative started
    CLOSED: [2020-11-04 Wed 12:33]
