#!/usr/bin/env bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

checkMemFree=$(awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# full text
	if (type == "swap")
		printf("%.1f\n", (swap_total-swap_free)/1024/1024)
	else
		printf("%.1f\n", mem_free/1024/1024)
}
' /proc/meminfo)

checkMemFull=$(awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# full text
	if (type == "swap")
		printf("%.1f\n", (swap_total-swap_free)/1024/1024)
	else
		printf("%.1f\n", mem_total/1024/1024)
}
' /proc/meminfo)

a=$(echo "print($checkMemFree/$checkMemFull >= 0.6)" | python3)
b=$(echo "print(0.25 <= $checkMemFree/$checkMemFull < 0.6)" | python3)
c=$(echo "print($checkMemFree/$checkMemFull < 0.25)" | python3)

if [ "$a" = "True" ]; then
	echo '<span foreground="#00ff00">[F]</span> MEM' $checkMemFree'G'
elif [ "$b" = "True" ]; then
	echo '<span foreground="#ffec00">[F]</span> MEM' $checkMemFree'G'
elif [ "$c" = "True" ]; then
	echo '<span foreground="#ff0000">[F]</span> MEM' $checkMemFree'G'
fi
