#!/bin/sh

pid=$(pgrep -x i3lock)
if [[ -z $pid ]]; then
  revert() {
  xset dpms 300 300 300
  }
  trap revert HUP INT TERM
  xset +dpms dpms 10 10 10
  sleep 0.1                                                
  scrot --quality 10 -o /tmp/screenshot.png
  convert /tmp/screenshot.png -blur 0x5 /tmp/screenshot.png
  i3lock -n -i /tmp/screenshot.png
  revert
fi
