[theme]
theme = "dracula"
[theme.overrides]
alternating_tint_bg = "#151515"

[icons]
icons = "awesome4"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
format = " $icon $utilization.eng(w:3) @ $frequency "

[[block]]
block = "temperature"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi) ($mem_used_percents.eng(w:1)) "

[[block]]
block = "disk_space"
format = " $icon $available ($percentage.eng(w:1)) "

[[block]]
block = "custom"
command = """wifi | grep -q '= on' && \
  echo '{\"icon\": \"net_wireless\", \"state\": \"Info\", \"text\": \"enabled\"}' || \
  echo '{\"icon\": \"net_wireless\", \"text\": \"disabled\"}'"""
interval = "once"
json = true
signal = 8

[[block]]
block = "net"
format = " $icon ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) "
inactive_format = ""
signal = 8

[[block]]
block = "battery"
format = " $icon $percentage {($time)|} "
driver = "upower"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m/%Y') "

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%R') "

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
format = " \uf11c $layout "
signal = 9
