#+STARTUP: overview
#+OPTIONS: ^:nil
#+OPTIONS: p:t

** Tasks
*** Next
**** TODO Update management scripts
***** update script which updates all submodules and git repos to latest upstream commits eg. ~make update~ and then pushes upstream
***** update script for ~emacs~, ~vim~ and ~pip~ packages
***** perhaps re-run ~make install.monix~ to check for conflicts, or ~--adopt~ them if required
****** this could be necessary with no more folding -> for example with abook and GTK-related configs
****** or make another script which checks and adopts all changes in filesystem, eg. ~make check~ and ~make sync~
***** dump ~pip --user~ package lists as well during update -> ~pip freeze --user~
***** update script for package lists and all relevant logs on ~monix~ repo with ~git push~ afterwards
***** coordinate all of these processes with ~monix~ tasks
***** implement workaround for files which get overwritten due to ~--no-folding~ in stow
****** EITHER use git commands and stow simulation to check for changes to dotfiles
****** OR try adopting and doing a git status check
****** OR try to fold directory which gets overwritten -> eg. emacs, gtk2/3, qt5ct, abook and others
****** OR consider purchasing a yubikey to manage GPG keys
****** need to add workflow to check this on system update -> or do this periodically via timer or to-do-note
****** think about how files are overwritten in ~dotfiles~ and whether folds are always necessary, eg. for ~mimeapps~ and ~abook~ 

*** Long-term
**** Backup
***** reduce size of ~personal~ directory to keep only important data 
***** optimize an elegant backup workflow of the ~personal~ directory with a script, possibly in the private repository
***** perhaps would be good to have a reminder own notes instead of an automatic backup event scheduled -> think of possible failures with wrong drive 
***** perhaps use tarballs with ~rsync~ to ensure only relevant data is updated
***** think of separating important and unimportant data -> only back up the important data
***** organize drive to ensure backups all make good sense
***** gnupg
****** only hard backups should be personal files and GPG keys for unlocking everything else
****** think of backup scheduling and structure for GPG, such as public/private keys and trust databases
****** consider printing key as final failsafe using ~paperkey~
***** emails
****** back up neomutt emails as well, since they could be good-to-keep

**** i3
***** port ~i3-cycle~ backend to ~i3ipc~ and ship everything to AUR/pypi: https://github.com/mota/i3-cycle/issues/3
***** replace ~pypi~ package(s) with this implementation
***** think about using xautolock/xss-lock to circumvent some manual pid checking and possibly extra sleep: https://github.com/i3/i3lock/issues/207

**** Monitor configuration
***** create ~AUR~ repository for alternative package management: https://github.com/phillipberndt/autorandr/issues/250
***** replace ~pypi~ package with this implementation

**** Neovim
***** Basic
****** migrate from vim to neovim to fix upstream issues related to ~terminfo~ and ~alacritty~: https://github.com/alacritty/alacritty/issues/919 
****** conditionally alias ~nvim~ to ~vim~ if it exists -> update preferences in applications to either ~nvim~ or ~vim~
****** conditional ~xterm-256color~ declaration inside ~.vimrc~ if ~nvim~ is not running
******* update variables referencing ~xterm-256color~ or ~vim~ in dotfiles if necessary
****** find good location to install ~suda~ plugin from ~nvim~ to overcome issue: https://github.com/neovim/neovim/issues/12103
***** Next
****** re-develop neovim configuration from the ground up by removing all unnecessary plugins 
****** sort out a clean way of updating all plugins as necessary: https://github.com/amix/vimrc/issues/637
******* this is no longer be necessary since plugins are regularly updated upstream

**** Emacs
***** Change emacs distribution
****** migrate to lightweight and lean personal emacs configuration which would be optimized with time such as with ~doom~ -> might help circumvent many bugs encountered such as those with ~latex~ and ~elpy~ compatibilities
****** work on script which updates all emacs packages during system update
***** Patch ~company-reftex~
****** think about improving workflow to handle spaces, make case unsensitive and parse bibliography codes better (eg. "doran2017does" from "do") in ~company-reftex-citation-candidates~, for development add package (eg. ~(company-reftex :location (recipe :fetcher github :repo "atreyasha/company-reftex"))~) in ~dotspacemacs-additional-packages~ and update packages, delete old package location 
***** Patch ~helm-company~
****** fix wrong argument error on ~helm-company~ post command hook -> linked to ~helm-company~ interaction with ~company-post-command~: see https://github.com/Sodel-the-Vociferous/helm-company/issues/21 -> fix would require looking at ~company-post-command~ to understand what is failing
***** Patch ~elpy~
****** issue of ~elpy~ hard-coded ~company~ backends -> this should instead be soft-coded and easily updated from upstream
***** Spacemacs
****** Improve autocompletions of latex layer: https://github.com/syl20bnr/spacemacs/issues/14134
******* wrong order of company-completions -> brute-force solution is to create new layer
******* lighter solution is to modify ~company-backends~ variable post-initialization -> perhaps with advice over latex init function
****** Automatically merge upstream changes to latex layer which are coped/modified

**** Neomutt 
***** reformat binding and unbinding schemes for each account to be more modular, consistent, portable and to re-use variables where possible
****** maybe can use for-loop with command-mode to create this quickly
****** consider removing junk for shortening configs
***** raise issue on similar keys being acculumated in help pages -> specifically when ~i~ and ~d~ are suffixed on commands
***** consider adding check-stats or sync-mailbox command after moving or copying -> to update all statistics -> maybe issue for ~mw~
***** improve other formatting with extended lines given ~named-mailbox~, and other optimizations with commands, see: https://github.com/jindraj/dotfiles/tree/master/.neomutt
****** consider integrating ~notmuch~ in the future
***** issue of specified subkey not being used: https://github.com/neomutt/neomutt/issues/2980
***** update exact subkey when this is fixed
**** Mimeapps/mailcap
***** add mailcap helpers in ~conf~ and coordinate with mimetypes
***** synchronize mime system program defaults to same as ranger's rifle
**** PGP public key
***** host public key on ~keys.openpgp.org~ or ~keybase.io~
***** add personal website page for accessing keys manually on GitHub or via specific keyserver (and mention not others)
***** consider adding PGP key-id to GitHub page
**** Qutebrowser
***** disable dpms/dim when video is playing: see bug report https://github.com/qutebrowser/qutebrowser/issues/5504
**** Generic
***** update configuration files with upstream changes (or remove upstream templates)
***** update script which does manual update checks on files which might require upstream updates -> perhaps perform a diff framework to accept/reject upstream changes -> eg. ~spacemacs~ latex layer modified files
***** examples include spacemacs, qutebrowser and ranger
