#+STARTUP: overview
#+OPTIONS: ^:nil
#+OPTIONS: p:t

** Tasks
*** Next
**** TODO System upgrade
***** add ~test~ commands for all repositories
****** use ~stow~ simulation without verbosity and check exit code
***** update all miscellaneous packages
****** update all submodules with ~make update~, including ~vim~ and ~emacs~
****** ~pip~ can be updated with ~pip install -U~ CLI
****** ~spacemacs~ packages would require manual command: https://emacs.stackexchange.com/questions/41786/update-spacemacs-packages-from-the-command-line
***** dump new ~pip --user~ package lists after update -> ~pip freeze --user~
***** use ~yay~ for system upgrade followed by miscellaneous upgrades and ~pip~ tracking
****** run all tests for three repositories and print these out clearly
****** consider piping output away since this could meddle with important messages such as ~pacman~ hooks outputs 

**** TODO Backup
***** Framework
****** perhaps use ~rsync~ with tarballs to ensure only relevant data is updated
****** clean external hard-drive and organize folders there
****** back-up ~personal~ directory, ~gnupg~ keys and neomutt email archives
******* think of any other important data to back up -> inspect drive for templates
******* consider moving mail archives to ~personal~ for easier backups
******* consider printing key as final failsafe using ~paperkey~
******* consider purchasing a yubikey to manage GPG keys
***** Scheduling
****** schedule backups with timer or via manual notes
****** think of script to backup and deploy
 
*** Long-term
**** Sync
***** implement ~sync~ in case repository tests fail
****** ~adopt~ files via stow and perform a git status check
****** force fold directory where file gets overwritten -> eg. gtk2/3, qt5ct etc.

**** i3
***** port ~i3-cycle~ backend to ~i3ipc~ and ship everything to AUR/pypi: https://github.com/mota/i3-cycle/issues/3
***** replace ~pypi~ package(s) with this implementation
***** think about using xautolock/xss-lock to circumvent some manual pid checking and possibly extra sleep: https://github.com/i3/i3lock/issues/207

**** Monitor configuration
***** create ~AUR~ repository for alternative package management: https://github.com/phillipberndt/autorandr/issues/250
***** replace ~pypi~ package with this implementation

**** Neovim
***** Basic
****** migrate from vim to neovim to fix upstream issues related to ~terminfo~ and ~alacritty~: https://github.com/alacritty/alacritty/issues/919 
****** conditionally alias ~nvim~ to ~vim~ if it exists -> update preferences in applications to either ~nvim~ or ~vim~
****** conditional ~xterm-256color~ declaration inside ~.vimrc~ if ~nvim~ is not running
******* update variables referencing ~xterm-256color~ or ~vim~ in dotfiles if necessary
****** find good location to install ~suda~ plugin from ~nvim~ to overcome issue: https://github.com/neovim/neovim/issues/12103
***** Next
****** re-develop neovim configuration from the ground up by removing all unnecessary plugins 
****** sort out a clean way of updating all plugins as necessary: https://github.com/amix/vimrc/issues/637
******* this is no longer be necessary since plugins are regularly updated upstream

**** Emacs
***** Change emacs distribution
****** migrate to lightweight and lean personal emacs configuration which would be optimized with time such as with ~doom~ -> might help circumvent many bugs encountered such as those with ~latex~ and ~elpy~ compatibilities
****** work on script which updates all emacs packages during system update
***** Patch ~company-reftex~
****** think about improving workflow to handle spaces, make case unsensitive and parse bibliography codes better (eg. "doran2017does" from "do") in ~company-reftex-citation-candidates~, for development add package (eg. ~(company-reftex :location (recipe :fetcher github :repo "atreyasha/company-reftex"))~) in ~dotspacemacs-additional-packages~ and update packages, delete old package location 
***** Patch ~helm-company~
****** fix wrong argument error on ~helm-company~ post command hook -> linked to ~helm-company~ interaction with ~company-post-command~: see https://github.com/Sodel-the-Vociferous/helm-company/issues/21 -> fix would require looking at ~company-post-command~ to understand what is failing
***** Patch ~elpy~
****** issue of ~elpy~ hard-coded ~company~ backends -> this should instead be soft-coded and easily updated from upstream
***** Spacemacs
****** Improve autocompletions of latex layer: https://github.com/syl20bnr/spacemacs/issues/14134
******* wrong order of company-completions -> brute-force solution is to create new layer
******* lighter solution is to modify ~company-backends~ variable post-initialization -> perhaps with advice over latex init function
****** Automatically merge upstream changes to latex layer which are coped/modified

**** Neomutt 
***** reformat binding and unbinding schemes for each account to be more modular, consistent, portable and to re-use variables where possible
****** maybe can use for-loop with command-mode to create this quickly
****** consider removing junk for shortening configs
***** raise issue on similar keys being acculumated in help pages -> specifically when ~i~ and ~d~ are suffixed on commands
***** consider adding check-stats or sync-mailbox command after moving or copying -> to update all statistics -> maybe raise issue/PR for ~mw~
***** improve other formatting with extended lines given ~named-mailbox~, and other optimizations with commands, see: https://github.com/jindraj/dotfiles/tree/master/.neomutt
****** consider integrating ~notmuch~ in the future
***** issue of repeated compose command after send: https://github.com/neomutt/neomutt/issues/2091
***** issue of specified subkey not being used: https://github.com/neomutt/neomutt/issues/2980
****** update exact subkey when this is fixed
       
**** PGP keys
***** host public key on ~keys.openpgp.org~ or ~keybase.io~
***** add personal website page for accessing keys manually on GitHub or via specific keyserver (and mention not others)
***** consider adding PGP key-id to GitHub page
**** Mimeapps/mailcap
***** add mailcap helpers in ~conf~ and coordinate with mimetypes
***** synchronize mime system program defaults to same as ranger's rifle
**** Qutebrowser
***** disable dpms/dim when video is playing: see bug report https://github.com/qutebrowser/qutebrowser/issues/5504
**** Generic
***** best way to foce-fold would be to stow all with ~--no-folding~ and then re-do with ~fold_stow~
***** update script which does manual update checks on files which might require upstream updates -> perhaps perform a diff framework to accept/reject upstream changes -> eg. ~spacemacs~ latex layer modified files
****** update configuration files with upstream changes (or remove upstream templates)
****** examples include spacemacs, qutebrowser and ranger
